language: java
jdk: 
- oraclejdk10

script: "mvn cobertura:cobertura"

after_success:
- bash <(curl -s https://codecov.io/bash)

  <plugin>
  <groupId>org.codehaus.mojo</groupId>
  <artifactId>cobertura-maven-plugin</artifactId>
  <version>2.7</version>
  <configuration>
  <formats>
  <format>html</format>
  <format>xml</format>
  </formats>
  <check />
  </configuration>
  </plugin>