language: java
jdk: 
- oraclejdk10

script: "mvn cobertura:cobertura"

after_success:
- bash <(curl -s https://codecov.io/bash)
- bash <(curl -s https://codecov.io/bash) -t 743fc5cd-fb2c-4dc7-9dfd-fdb78f7ad756
